/**
 * Workflow Scout — Playwright Script Exporter
 *
 * Converts a DetectedPattern into a runnable Playwright test script
 * that reproduces the detected browser workflow.
 */

import { DetectedPattern, PatternStep } from "./pattern-detector";

// ── Helpers ────────────────────────────────────────────────────────────────────

function escapeString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n");
}

function indent(lines: string[], level: number): string {
  const pad = "  ".repeat(level);
  return lines.map((l) => (l.trim() ? `${pad}${l}` : "")).join("\n");
}

function buildStepCode(step: PatternStep, index: number): string[] {
  const lines: string[] = [];
  const comment = `// Step ${index + 1}: ${step.description}`;
  lines.push(comment);

  switch (step.type) {
    case "navigation":
      lines.push(`await page.goto('${escapeString(step.urlPattern)}');`);
      lines.push(`await page.waitForLoadState('networkidle');`);
      break;

    case "click":
      if (step.selector) {
        lines.push(`await page.locator('${escapeString(step.selector)}').click();`);
      } else {
        lines.push(`// TODO: Add selector for click target`);
        lines.push(`// await page.locator('selector').click();`);
      }
      break;

    case "form_submit":
      if (step.formFields) {
        for (const [name, value] of Object.entries(step.formFields)) {
          if (value === "[REDACTED]") {
            lines.push(
              `await page.locator('[name="${escapeString(name)}"]').fill(process.env.FORM_${name.toUpperCase()} || '');`
            );
          } else {
            lines.push(
              `await page.locator('[name="${escapeString(name)}"]').fill('${escapeString(value)}');`
            );
          }
        }
      }
      if (step.selector) {
        lines.push(`await page.locator('${escapeString(step.selector)}').evaluate(form => form.submit());`);
      } else {
        lines.push(`await page.locator('form').evaluate(form => form.submit());`);
      }
      lines.push(`await page.waitForLoadState('networkidle');`);
      break;

    case "input_change":
      if (step.selector) {
        lines.push(
          `await page.locator('${escapeString(step.selector)}').fill('${escapeString(step.formFields?.["value"] || "")}');`
        );
      }
      break;

    default:
      lines.push(`// Unknown step type: ${step.type}`);
  }

  lines.push(""); // blank line between steps
  return lines;
}

// ── Main Export Function ───────────────────────────────────────────────────────

export interface PlaywrightExportOptions {
  /** Use headed browser mode. Default: false */
  headed?: boolean;
  /** Base URL to use (replaces URL patterns). Default: none */
  baseUrl?: string;
  /** Browser to use. Default: "chromium" */
  browser?: "chromium" | "firefox" | "webkit";
}

/**
 * Convert a DetectedPattern into a Playwright test script string.
 */
export function exportToPlaywright(
  pattern: DetectedPattern,
  options: PlaywrightExportOptions = {}
): string {
  const { headed = false, browser = "chromium" } = options;

  const stepLines: string[] = [];
  for (let i = 0; i < pattern.steps.length; i++) {
    stepLines.push(...buildStepCode(pattern.steps[i], i));
  }

  const script = `/**
 * Playwright automation script
 * Generated by Workflow Scout from pattern: ${pattern.label}
 * Pattern ID: ${pattern.id} | Frequency: ${pattern.frequency}x | Confidence: ${Math.round(pattern.confidence * 100)}%
 */

import { ${browser}, Browser, Page } from 'playwright';

async function run(): Promise<void> {
  const browser: Browser = await ${browser}.launch({ headless: ${!headed} });
  const context = await browser.newContext();
  const page: Page = await context.newPage();

  try {
${indent(stepLines, 2)}
    console.log('Workflow completed successfully.');
  } catch (error) {
    console.error('Workflow failed:', error);
    throw error;
  } finally {
    await browser.close();
  }
}

run().catch(console.error);
`;

  return script;
}

/**
 * Export as a Playwright Test format (for use with @playwright/test).
 */
export function exportToPlaywrightTest(
  pattern: DetectedPattern,
  options: PlaywrightExportOptions = {}
): string {
  const stepLines: string[] = [];
  for (let i = 0; i < pattern.steps.length; i++) {
    stepLines.push(...buildStepCode(pattern.steps[i], i));
  }

  const script = `/**
 * Playwright Test automation
 * Generated by Workflow Scout from pattern: ${pattern.label}
 */

import { test, expect } from '@playwright/test';

test('${escapeString(pattern.label)}', async ({ page }) => {
${indent(stepLines, 1)}
});
`;

  return script;
}
